---
title:    "A longitudinal modeling framework for depression trajectories in the Spanish adult population"
date:     "7 sep, 2023"
author:   "Daniel Morillo, Ph.D."
format:
  revealjs:
    fig-align:               center
    fig-cap-location:        bottom
    incremental:             true
    link-external-newwindow: true
    preview-links:           true
    preload-iframes:         true
    self-contained:          true
    theme:                   simple
    view-distance:                3
bibliography: ../www/rp-presentation.bib
---

## Introduction

-   one in five individuals will experience one episode at some point in their
    lifetime (WHO, 2012)

-   the most likely period for the onset of the first episode of depression
    extends from 20s to mid-40s, a significant proportion of individuals
    experience their first episode at older ages (i.e. 60+ ages) (Hasin et al.,

    2005) 

-   Late (vs. early) onset depression has a distinctive impact on health and
    wellbeing.

-   Depression in older adults is associated with increased risk of morbidity,
    decreased physical, cognitive and social functioning, and higher mortality
    (McLaughlin, 2011).

-   investigating the course of depression and/or depressive symptoms in
    longitudinal prospective studies with the aim of understanding its
    determinants and which trajectory patterns are associated with worse
    outcomes (i.e. poor cognitive function, higher rates of suicidal behaviour,
    and mortality) is needed

## Objectives

-   because of the serious functional limitations, long-term care needs, and
    substantial financial and societal costs of depression, it is relevant to
    increase our knowledge about the factors that determine the onset and
    maintenance of depression as well as the significance of symptom timing to
    establish associations with other health-related outcomes and for effective
    treatment of depressed older adults.

-   differ by gender, marital status, socioeconomic factors, lifestyle
    behaviours, cognitive reserve, or the presence of physical or mental
    comorbidities among other variables (Köhler et al., 2018), while the
    time-varying impact of these factors over the old age are yet unknown (e.g.
    cognitive function).

## Topic

<br>

> Diverse trajectory patterns of depression will be identified with a relevant
> role of time-varying determinants (e.g. cognitive function) on the severity of
> depressive symptoms.

::: fragment
### *Modeling and predicting depression trajectories*
:::

## Context

<br>

Project [*Edad con Salud*](http://edadconsalud.com/?lang=en)

-   Longitudinal cohort Ageing study

-   Two cohorts: original (2011) and refreshment (2019)

-   Waves: 4 (original cohort), 2 + lockdown substudy (refreshment sample)

-   One more wave projected for each cohort

::: fragment
(More details in @lara2022)
:::

## Research questions {.smaller}

<br>

**Primary RQ:**

-   Do there exist different, theoretically relevant, trajectories of
    depression, throughout the course of the lifetime?

::: fragment
**Secondary RQQ:**
:::

1.  Do certain time-invariant (e.g. sociodemographics) or time-varying (e.g.
    cognitive function, treatment(s)) covariates predict the trajectories of the
    individuals?

2.  How does depression relate to health outcomes (i.e., disease burden,
    disability, and mortality)?

3.  What has been the impact (shock) of the pandemic/lockdown measures on the
    different depression trajectory classes?

## Measures

<br>

On Cohort 2011:

-   **Primary outcome:** ICD10-based 12-month depressive episode (dichotomous /
    severity-coded)

-   **Covariates:** sociodemographics (age, sex, SES, education), cognitive
    function, loneliness (...?)

-   **Other relevant outcomes:** health score, disability, mortality

## Modeling approach {.smaller}

<br>

**Group-based Trajectory Modeling** [@nagin1999]

<br>

::: {style="text-align: center;"}
![Estimated probability of 12-month MDE
[@xiang2019]](../www/Xiang-Cheng-2019_Figure-1.jpg){fig-align="center"
width="60%"}
:::

## Modeling approach

<br>

**Advantages:**

-   Covariates may be included in the model

-   May account for nonrandom attrition [e.g. mortality, @haviland2011]

-   Multiple/joint trajectories can be modeled [@nagin2001]

::: fragment
**Alternatively:** Growth Mixture Modeling [@muthén1999] (for SRQ 3?)
:::

## References {.smaller}

